### ISSUE TITLE
Caps Lock + Escape does not enable Capslock

### ISSUE THREAD

**Issue by hwangdylan** [Vonng/Capslock#12]
As the title states, pressing Caps Lock + Escape does not enable the actual CapsLock. The configuration file is the default config file and there is no extra modifications.

**Comment by swordencao** [comment]
Your macOS version? I'm using `10.14.4 (18E2034)` and it works fine.

**Comment by hwangdylan** [comment]
Yes I am running `10.14.4` and it does not work. I have tried to set it myself in the modifications but it has not fixed the issue.

**Comment by willzhqiang** [comment]
I am also fine with this config.

**Comment by hwangdylan** [comment]
what computer do you have? I have a touchbar version of the mac and when i try to use Caps Lock + Escape on the built in keyboard it does not work, but when I use an external keyboard with a physical escape button then it works. Potentially this is a  bug? Any workarounds would be appreciated.

**Comment by swordencao** [comment]
> what computer do you have? I have a touchbar version of the mac and when i try to use Caps Lock + Escape on the built in keyboard it does not work, but when I use an external keyboard with a physical escape button then it works. Potentially this is a bug? Any workarounds would be appreciated.

Not working as well on macOS `10.15.3 (19D76)` MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports), Touch-bar version.

**Comment by Vonng** [comment]
@hwangdylan 

From the built-in Karabiner-EventViewer, it do emit a caps_lock event. However the effect in MacOS is quite tricky. 

* If you press CapsLock + Escape very quickly, it's actual effect is switching your input source.
* But if you hold that a little bit longer, it will work as a real CapsLock

Hope it help
