### ISSUE TITLE
return key

### ISSUE THREAD

**Issue by ehrlichja** [Vonng/Capslock#13]
This is great! Any thoughts on how to remap the return key to something else? its still a far stretch (dealing with some RMI here).

**Comment by Vonng** [comment]
@ehrlichja  thanks~~ 
Any suggestions? 😉

> This is great! Any thoughts on how to remap the return key to something else? its still a far stretch (dealing with some RMI here).

**Comment by Vonng** [comment]
Now the latest version define enter into five mouse buttons.

https://github.com/Vonng/Capslock/blob/master/mac_v3/capslock.yml#L520
