### ISSUE TITLE
Readme的Applications 部分介绍有重复

### ISSUE THREAD

**Issue by willzhqiang** [Vonng/Capslock#14]
Open Dictionary 介绍了两次。
另外，Application这个似乎title的级别和上面的Bash Control和下面的Functional有点不一致。
当然，我可能有点吹毛求疵了。

**Comment by suliveevil** [comment]
> Open Dictionary 介绍了两次。
> 另外，Application这个似乎title的级别和上面的Bash Control和下面的Functional有点不一致。
> 当然，我可能有点吹毛求疵了。

fork 以后自己改吧

**Comment by Vonng** [comment]
fixed
