### ISSUE TITLE
Readme 里面F15的描述和实际功能不一致

### ISSUE THREAD

**Issue by willzhqiang** [Vonng/Capslock#15]
Readme里面写的是Play or Pause，但我看代码其实是mute，这两者还是有点区别的。Mute对应的是F10，而Play or Pause则是暂停播放设备，理论上应该和F8的code一样。

**Comment by willzhqiang** [comment]
⌘; Semicolon | ! | Colon
-- | -- | --
这个map的应该是`:`，而不是`!`，应该也是笔误

**Comment by Vonng** [comment]
感谢指正。
最近进行了一次大的校订，已经修复哈～。
