### ISSUE TITLE
Question regarding keyboard overview guide?

### ISSUE THREAD

**Issue by dimitrieh** [Vonng/Capslock#17]
Dear @Vonng 

A quick question. Is the keyboard overview guide of your own making or do you use a tool to generate this?

kind regards,

**Comment by Vonng** [comment]
Well, it's hand made 🤣

Source file:  https://github.com/Vonng/Capslock/blob/master/images/keyboard.html

**Comment by dimitrieh** [comment]
Thanks so much, exactly what I was looking for! 🙏
