### ISSUE TITLE
请问具体的开源协议?

### ISSUE THREAD

**Issue by LiangWei88** [Vonng/Capslock#18]
你好, 你的开源协议里面使用了 WTFPL
但是上面又有一个声明 changing it is not allowed.

请问我再你的代码里面截取一些部分放入我的一个开源项目当中是被允许的吗?
谢谢

**Comment by Vonng** [comment]
WTFPL的原意应指不允许修改WTFPL本身。我的本意就是字面意义：
想干嘛就干嘛 😆
