### ISSUE TITLE
Capslock hold doesn't work as Ctrl in Vim

### ISSUE THREAD

**Issue by marko999** [Vonng/Capslock#19]
OS: MacOS Catalina 10.15.4
Karabiner-Elements with CapsLock imported

CapsLock as Hyper, my case Ctrl works nicely,  for example in ITerm2 if I hold Ctrl and press c it interrupts current process...
But in Vim, it works nicely as tap->ESC, using this feature a lot, but when holding Ctrl I expect to be used as Vim <C>(Ctrl) and it doesn't work...

What I am doing wrong or there are additional configuration needs to be added for Vim?

**Comment by milushov** [comment]
@marko999 did you try to play with [frontmost_application_unless](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application) setting?

**Comment by Vonng** [comment]
I've updated this script to v3.

Only a small portion of keys are maps to ^ control. e.g (`ZDC`).

https://github.com/Vonng/Capslock#terminal-control
