### ISSUE TITLE
keyFunc_esc

### ISSUE THREAD

**Issue by qiao1025566574** [Vonng/Capslock#20]
请问可以实现esc这样的效果吗？比如按下caps_space=keyFunc_esc。想用cap和space代替esc，但好像这样写并不行，这个keyFunc是内置的吗？可以自定义吗？

**Comment by Vonng** [comment]
当然可以自定义，所有的改键规则都定义在 [capslock.yml](https://github.com/Vonng/Capslock/blob/master/mac_v3/capslock.yml) 中。
默认就是把单击Capslock映射为Escape的。
