### ISSUE TITLE
无法进入hyper模式

### ISSUE THREAD

**Issue by injoylin** [Vonng/Capslock#26]
问题:
长按住 caps lock键无法进入hyper模式,键盘大写灯不亮,没有任何作用,删除配置后,长按caps lock键盘,灯会亮,大写功能正常
如果一直按住 caps lock键不放,操作其他键,可以达到hyper模式的效果

**Desktop (please complete the following information):**
 - mac os 10.14
 - 配置文件3.03
 - Karabiner 12.10

**Comment by Vonng** [comment]
Isn't this exactly the expected behavior? Hold Caps and click Esc to switch to the actual CAPSLOCK state
这不正是期待的行为吗？长按 Caps 之后单击 Esc 切换真正的Capslock状态
