### ISSUE TITLE
sysdiagnose is triggered frequently

### ISSUE THREAD

**Issue by amjltc295** [Vonng/Capslock#30]
For some reason MacOS sysdiagnose is triggered frequently after installing Karabiner with Capslock. 
Similar problem is also reported here https://github.com/pqrs-org/Karabiner-Elements/issues/1107 but I don't know how to integrate with this module. It is also a bit hard to reproduce as there's no instant feedback. Sysdiagnose usually runs for a while before it generates reports under `/private/var/tmp`. Wonder if anyone has the same problem and how to fix it.

**Comment by ch4li** [comment]
[[how-do-you-get-system-diagnostic-files-from-macos]](https://apple.stackexchange.com/questions/59917/how-do-you-get-system-diagnostic-files-from-macos) 

May it help to understand this key shot problem.

If you want to DIY the CapsLock config, follow my simple steps on MacOS:

- download `capslock.json` in repository here, or git clone, edit it and move it like below

- `vim ~/opt/config/Capslock/mac/capslock.json`

- Karabine - complex-rules - removeALL && enableAll

There are more details on Homepage Documents

**Comment by amjltc295** [comment]
> [[how-do-you-get-system-diagnostic-files-from-macos]](https://apple.stackexchange.com/questions/59917/how-do-you-get-system-diagnostic-files-from-macos)
> 
> May it help to understand this key shot problem.
> 
> If you want to DIY the CapsLock config, follow my simple steps on MacOS:
> 
> * download `capslock.json` in repository here  (or git clone), edit it and move it like below
> * `vim ~/opt/config/Capslock/mac/capslock.json`
> * `cp -R ~/opt/config/Capslock/mac/capslock.json ~/.config/karabiner/assets/complex_modifications`
> * Karabine - complex-rules - removeALL && enableAll
> 
> There are more details on Homepage Documents

Thanks for sharing. I do know that sysdiagnose could be triggered by `shift+control+option+command+.`. However, I still don't understand why/how it is triggered after I install this repo and how to fix it. 

I did not change the rules related to `.`. I did customize it a bit but they are all about different mappings, like mapping "Capslock + f" to Enter, nothing more complicated

**Comment by Vonng** [comment]
Thank you for your feedback.
The same problem has bothered me before, and now I know what it is.
I will see if there is a way to work around this.

**Comment by amjltc295** [comment]
Hi, is there any update on this?

**Comment by amjltc295** [comment]
Hi I have some update on this -- setting `shift+control+option+command+.` and `shift+control+option+command+,` to delete-words-after is fine. It would not trigger sysdiagnose. However, when pressing `Capslock` after `.` (I set `Capslock + f` to be enter, so this happens quite often when changing directory), sysdiagnose would be triggered. I haven't found a way to fix it.

Some other tips:
* When triggering sysdiagnose, the screen would blink white once
* When already triggered, sysdiagnose would not be triggered again
* When triggered, one can open Activity Monitor and search for `sysdiagnose` to force-quit it, and it can be triggered again.

**Comment by amjltc295** [comment]
Update: Mac sysdiagnose is triggered by `Command + Option + Shift + Control + Period (.)`. 
To avoid triggering it, can remove all the "right_control". For example: change the Capslock from 
```
                                         "modifiers": [
                                             "right_command",
                                             "right_control",
                                             "right_option"
                                         ]
```
to
```
                                         "modifiers": [
                                             "right_command",
                                             "right_option"
                                         ]
```
