### ISSUE TITLE
caps + esc 无法切换大小写

### ISSUE THREAD

**Issue by seyoatda** [Vonng/Capslock#31]
win10 下，
caps + esc 无法切换大小写
caps + space 无法切换输入法，  但是 使用  caps + shift + L 居然能切换输入法中英文模式，这个功能在说明文档里并没有看到

使用的是 win10下 exe 直接使用，没有用 ahk
以及，键盘图上展示的是否为 mac 键盘？对于windows键盘有无对应的按键。尝试了如 shift / alt / ctrl 的组合，但是有些文档里给出的效果没法使用出来。所以我无法确实是哪里出现bug还是我组合按得不正确

**Comment by Vonng** [comment]
Windows version is no longer maintained. The doc is for MacOS only....

**Comment by seyoatda** [comment]
> Windows version is no longer maintained. The doc is for MacOS only....

bad news
