### ISSUE TITLE
移动至行首/行尾

### ISSUE THREAD

**Issue by HaoshuaiXu** [Vonng/Capslock#33]
请问如何实现移动至行首/行尾，有时候蛮需要这个操作的，自己没有找到相应的键位，烦请赐教，非常感谢！

**Comment by miozus** [comment]
亲，详见官方文档 

[导航功能](http://capslock.vonng.com/zh/docs/usage/navigation/) 



`capslock` + `I` 跳至行首
`capslock` + `O` 跳至行尾

**Comment by HaoshuaiXu** [comment]
谢谢深夜回复！

但是我在Sublime Text 4和Mail.app中都不起作用，在Edge上变成了移动滚轮……
系统是macOS 10.15.7。

**Comment by miozus** [comment]
🤔 针对 uiop ，我专门对不同编辑器做过测试

[一张草稿纸](https://www.notion.so/PageDown-e9d5f8bf4ca9496ea177177ef810cbc5)

结果体验总归不能统一，尽管我们输入一样的键，因为不同的软件遵循不同的标准，有的甚至混同。比如 Mac ，像 Emacs ：

1）你可以忘掉capslock，试试最原始的 `Control` + `A` / `E`

2）或者查看你的编辑器跳转行首行尾的快捷键，重设成 1）。

3）忘掉前面的，用 vim 与生俱来的`^` 和 `$`。

看你的权衡和妥协。

**Comment by HaoshuaiXu** [comment]
明白了，非常感谢解答！
