### ISSUE TITLE
【访问不了需要备案】欢迎来到CapsLock中文文档

### ISSUE THREAD

**Issue by miozus** [Vonng/Capslock#34]
http://capslock.vonng.com/zh/docs/

> 网站暂时无法访问
该网站未根据工信部相关法律规则进行备案

恨自己没下载

**Comment by miozus** [comment]
https://github.com/Vonng/Capslock/blob/master/README_ZH.md

突然发现项目主页就有说明书，还能跳转。

开心

**Comment by Vonng** [comment]
备案被吃了，这确实是一个 issue……

**Comment by Vonng** [comment]
Resolved.
