### ISSUE TITLE
使用数字键拷贝粘贴重复的bug

### ISSUE THREAD

**Issue by zhou-xiao-bai** [Vonng/Capslock#37]
你好，当我学习使用数字键1，2 进行分别拷贝粘贴的时候，遇到了这样一个bug

我分别用*+command+1 和*+command+2去拷贝不同的文本，
然后用*+command+1去粘贴，然后粘贴的是文本1，
然后用*+command+2去粘贴，这时候第一次粘贴的还是文本1，第二次粘贴以及之后才是文本2，反过来也是如此。

我使用的是mac12.0.1 m1芯片的笔记本，期望你的回复，感谢

**Comment by suliveevil** [comment]
我觉得你的流程描述不太清晰，键盘映射和剪贴板管理应该是两个流程的配合。

**Comment by Vonng** [comment]
本地文件IO没有键盘响应那么快，所以有时候IO慢了就容易出现还没读到剪贴板，就粘贴出来了前一次的结果，通常第二次粘贴就好了……

我个人觉得这个是一个占位的凑数功能，只是偶尔用用，最好是和专业的剪贴板软件配合。

**Comment by zhou-xiao-bai** [comment]
明白了，感谢两位大佬的解答
