### ISSUE TITLE
Mac下应用捷径无法切换到已打开应用

### ISSUE THREAD

**Issue by flymin** [Vonng/Capslock#38]
**Describe the bug**
`open -a $APPLICATION` can only open new windows but not switch to bring the opened windows foreground.

**To Reproduce**
Steps to reproduce the behaviour:
1. open a finder window
2. go to another desktop
3. press the key-bind to open the finder
4. focus is moved to the finder window, but the window is not shown (the desktop does not change)

**Expected behaviour**
desktop containing finder window should be moved foreground.

**Desktop (please complete the following information):**
 - Mac OS 11.6

**Additional context**
I tested that google chrome can work well, but finder/vscode cannot.

**Comment by ShortTailedRat** [comment]
我已经收到邮件，有空多联系~~

**Comment by Vonng** [comment]
Can't reproduce on my environment. 

Since `open -a` 's behavior is not controlled by karabiner at all.

It moves existing window to foreground and open new windows if not exists.

Maybe there's something wrong with configuration , privilege or application path

**Comment by flymin** [comment]
It seems like a system bug. I will close this.

Thanks.
