### ISSUE TITLE
Caps Lock + Escape manipulator missing

### ISSUE THREAD

**Issue by huzecong** [Vonng/Capslock#4]
The "Caps Lock + Escape" manipulator seems to be missing in "Misc". An implementation of the proposed manipulator is as follows:
```json
{
  "type": "basic",
  "from": {
    "key_code": "escape",
    "modifiers": {
      "mandatory": [
        "right_command",
        "right_control",
        "right_shift",
        "right_option"
      ],
      "optional": [
        "caps_lock"
      ]
    }
  },
  "to": [
    {
      "key_code": "caps_lock"
    }
  ]
}
```
With `caps_lock` set as an optional modifier, it will not be difficult to turn Caps Lock off.

**Comment by Vonng** [comment]
That's great. thanks a log~. Added it in new commit.
