### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by zeefan1555** [Vonng/Capslock#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShortTailedRat** [comment]
我已经收到邮件，有空多联系~~

**Comment by suliveevil** [comment]
什么意思？不会用 Karabiner-Elements？

**Comment by zeefan1555** [comment]
抱歉，发错了





------------------ 原始邮件 ------------------
发件人: suliveevil ***@***.***&gt;
发送时间: 2022年3月4日 05:28
收件人: Vonng/Capslock ***@***.***&gt;
抄送: zeefan1555 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Vonng/Capslock] 能否开发mac 版本的？ (Issue #41)





 
什么意思？不会用 Karabiner-Elements？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vonng** [comment]
https://github.com/Vonng/Capslock/tree/master/mac_v3
