### ISSUE TITLE
Similar effects can be achieved on linux  (keyd)

### ISSUE THREAD

**Issue by jqtmviyu** [Vonng/Capslock#56]
https://github.com/rvaiya/keyd

simple example

```
[ids]

*

[main]
capslock = overload(capslock_layer, esc)

[capslock_layer]

esc = capslock

h = left
j = down
k = up
l = right

u = pageup
p = pagedown
i = home
o = end

m = backspace
```

**Are there more linux users would like to work together to improve this profile?**

**Comment by ShortTailedRat** [comment]
我已经收到邮件，有空多联系~~

**Comment by jqtmviyu** [comment]
I found myself using `vim` more often for text editing in Linux, and `shell` has its own common rules. I'm using the `hyprland ` desktop environment, which also has shortcut key functionality. The simple script provided above seems to be enough for my use case.

**Comment by jqtmviyu** [comment]
Another application that can achieve similar effects is xremap, but I haven't tried it. Those who are interested can give it a try.
