### ISSUE TITLE
How do you generate the keyboard images?

### ISSUE THREAD

**Issue by Franchise712** [Vonng/Capslock#61]
Hi! This is a great product! Can you let me know how you generate the keyboard images? They're really great! Thanks!

<img width="1181" alt="image" src="https://github.com/Vonng/Capslock/assets/35365779/c3ddf25b-ce0b-4163-a781-6af500eea342">

**Comment by Vonng** [comment]
Well that image is generated with HTML & CSS:

https://github.com/Vonng/Capslock/blob/5b17a11522ac67e518939de07557d49243265fbe/mac/images/capslock-v3.html
